# Generated by Django 6.0.5 on 2026-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacao", "0004_paciente_bairro_paciente_cep_paciente_cpf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacaoatendimento",
            name="data_consulta",
            field=models.DateField(blank=True, null=True),
        ),
    ]
