# Generated by Django 5.2.14 on 2026-05-25 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_anotacaoatendimento_data_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaIAClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('contexto', models.TextField(blank=True, null=True)),
                ('resultado_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_ia', to='avaliacao.paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_ia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackConsultaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('julgamento', models.CharField(choices=[('acerto', 'Acerto clínico'), ('parcial', 'Parcialmente útil'), ('erro', 'Erro clínico')], max_length=20)),
                ('peso', models.SmallIntegerField(default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_ia', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='avaliacao.consultaiaclinica')),
            ],
        ),
    ]
