# Generated by Django 5.2.14 on 2026-06-05 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0006_consultaiaclinica_feedbackconsultaia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_atendimento', 'Em atendimento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=30)),
                ('observacoes_agendamento', models.TextField(blank=True, null=True)),
                ('anotacoes_profissional', models.TextField(blank=True, null=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='avaliacao.paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_atendimento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
